### ISSUE TITLE
【建议】对 README.md 进行内容修改

### ISSUE THREAD

**Issue by NoctuG** [fangaso/server-status-panel#1]
您似乎应该将内容修改为“对第18行进行修改”，否则容易引起误会。同时将按钮内代码改为
```
[![Deploy to Cloudflare Workers](https://deploy.workers.cloudflare.com/button?paid=true)](https://deploy.workers.cloudflare.com/?url=https://github.com/Fangaso/SSP2022&paid=true)
```
否则在 `Authorize GitHub with Workers` 后不能正常出现 `Configure Cloudflare Account` 的选项（如下图所示）
<img width="553" alt="image" src="https://user-images.githubusercontent.com/49110788/179990908-5abeca5d-a2de-45e6-b1cd-377651d61288.png">

**Comment by fangaso** [comment]
感谢您的提议，已更改。谢谢！
